name: Cypress Test on Edge

on:
  repository_dispatch:
    types: [edge]

jobs:
  Edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Windows Edge
        uses: cypress-io/github-action@v4
        with:
          browser: edge
