name: Cypress Test on Electron

on:
  repository_dispatch:
    types: [electron]

jobs:
  electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Electron
        uses: cypress-io/github-action@v4
