name: Cypress Test on Firefox

on:
  repository_dispatch:
    types: [firefox]

jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Firefox
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
